import { initializeApp } from 'firebase/app';
import { getFirestore, doc, setDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyDeTLFptLL9WXJ-4Fd0mgMGP1wBNpZdPJI",
  authDomain: "pavithra-bandhan.firebaseapp.com",
  projectId: "pavithra-bandhan",
  storageBucket: "pavithra-bandhan.firebasestorage.app",
  messagingSenderId: "274283657746",
  appId: "1:274283657746:web:8617922cba32352fe5f6cb"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const initialProfiles = [
  {
    _id: 'usr_suyash',
    user: {
      _id: 'usr_suyash',
      fullName: 'Suyash Narade',
      email: 'suyash@example.com',
      mobile: '9876543210',
      gender: 'male',
      isVerified: true,
      status: 'active',
      role: 'user',
    },
    profileId: 'PB-10024',
    age: 26,
    gender: 'male',
    height: "5'10\"",
    maritalStatus: 'never_married',
    religion: 'Hindu',
    caste: 'Maratha',
    subCaste: 'Deshmukh',
    motherTongue: 'Marathi',
    city: 'Kolhapur',
    state: 'Maharashtra',
    country: 'India',
    education: 'B.Tech Computer Science',
    college: 'COEP Pune',
    occupation: 'Senior Software Engineer',
    company: 'Tech Solutions India',
    income: '15-20 LPA',
    fatherOccupation: 'Government Officer (Retd)',
    motherOccupation: 'Homemaker',
    brothers: 1,
    sisters: 0,
    familyType: 'nuclear',
    familyValues: 'moderate',
    aboutMe: 'Sophisticated engineer passionate about technology, Indian classical music, and traveling. Looking for an educated, understanding life partner with strong family values.',
    biodataUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    biodataFileName: 'Suyash_Narade_Biodata.pdf',
    biodataVisibility: 'connections_only',
    primaryPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    ],
    photoVisibility: 'public',
    completionPercentage: 95,
    isVerified: true,
    isFeatured: true,
    matchPercentage: 92,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_priya',
    user: {
      _id: 'usr_priya',
      fullName: 'Priya Kulkarni',
      email: 'priya@example.com',
      mobile: '9876543211',
      gender: 'female',
      isVerified: true,
      status: 'active',
      role: 'user',
    },
    profileId: 'PB-10025',
    age: 24,
    gender: 'female',
    height: "5'5\"",
    maritalStatus: 'never_married',
    religion: 'Hindu',
    caste: 'Brahmin',
    subCaste: 'Deshastha',
    motherTongue: 'Marathi',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    education: 'M.Sc Data Science',
    college: 'Fergusson College Pune',
    occupation: 'Data Scientist',
    company: 'Global Analytics Inc',
    income: '12-15 LPA',
    fatherOccupation: 'Bank Manager',
    motherOccupation: 'High School Teacher',
    brothers: 0,
    sisters: 1,
    familyType: 'joint',
    familyValues: 'traditional',
    aboutMe: 'Warm, career-oriented yet traditional Marathi girl. Enjoy reading, classical dance, and family gatherings.',
    biodataUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    biodataFileName: 'Priya_Kulkarni_Biodata.pdf',
    biodataVisibility: 'connections_only',
    primaryPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    ],
    photoVisibility: 'public',
    completionPercentage: 90,
    isVerified: true,
    isFeatured: true,
    matchPercentage: 88,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_rohit',
    user: {
      _id: 'usr_rohit',
      fullName: 'Rohit Patil',
      email: 'rohit@example.com',
      mobile: '9876543212',
      gender: 'male',
      isVerified: true,
      status: 'active',
      role: 'user',
    },
    profileId: 'PB-10026',
    age: 28,
    gender: 'male',
    height: "5'11\"",
    maritalStatus: 'never_married',
    religion: 'Hindu',
    caste: 'Maratha',
    subCaste: '96 Kuli',
    motherTongue: 'Marathi',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    education: 'MBA Finance',
    college: 'JBIMS Mumbai',
    occupation: 'Investment Banker',
    company: 'HDFC Securities',
    income: '25-30 LPA',
    fatherOccupation: 'Businessman',
    motherOccupation: 'Homemaker',
    brothers: 1,
    sisters: 1,
    familyType: 'nuclear',
    familyValues: 'moderate',
    aboutMe: 'Ambitious professional who balances work and life. Fitness enthusiast and avid reader.',
    primaryPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    photos: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80'],
    photoVisibility: 'public',
    biodataVisibility: 'public',
    completionPercentage: 85,
    isVerified: true,
    isFeatured: true,
    matchPercentage: 85,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_ananya',
    user: {
      _id: 'usr_ananya',
      fullName: 'Ananya Joshi',
      email: 'ananya@example.com',
      mobile: '9876543213',
      gender: 'female',
      isVerified: true,
      status: 'active',
      role: 'user',
    },
    profileId: 'PB-10027',
    age: 25,
    gender: 'female',
    height: "5'4\"",
    maritalStatus: 'never_married',
    religion: 'Hindu',
    caste: 'Brahmin',
    subCaste: 'Kokanastha',
    motherTongue: 'Marathi',
    city: 'Nashik',
    state: 'Maharashtra',
    country: 'India',
    education: 'B.Arch Architecture',
    college: 'Sir JJ College of Architecture',
    occupation: 'Architect / Interior Designer',
    company: 'Studio Design Mumbai',
    income: '10-12 LPA',
    fatherOccupation: 'Doctor (MD)',
    motherOccupation: 'Doctor (Gynaecologist)',
    brothers: 0,
    sisters: 0,
    familyType: 'nuclear',
    familyValues: 'liberal',
    aboutMe: 'Creative architect passionate about art, interior spaces, and trekking in Maharashtra forts.',
    primaryPhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    photos: ['https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80'],
    photoVisibility: 'public',
    biodataVisibility: 'public',
    completionPercentage: 88,
    isVerified: true,
    isFeatured: true,
    matchPercentage: 86,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_aditya',
    user: {
      _id: 'usr_aditya',
      fullName: 'Aditya Deshmukh',
      email: 'aditya@example.com',
      mobile: '9876543214',
      gender: 'male',
      isVerified: true,
      status: 'active',
      role: 'user',
    },
    profileId: 'PB-10028',
    age: 29,
    gender: 'male',
    height: "6'0\"",
    maritalStatus: 'never_married',
    religion: 'Hindu',
    caste: 'Maratha',
    subCaste: 'Deshmukh',
    motherTongue: 'Marathi',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    country: 'India',
    education: 'MD General Medicine',
    college: 'GMC Aurangabad',
    occupation: 'Consultant Physician',
    company: 'City Multi-Specialty Hospital',
    income: '30+ LPA',
    fatherOccupation: 'Civil Judge (Retd)',
    motherOccupation: 'Professor',
    brothers: 1,
    sisters: 0,
    familyType: 'joint',
    familyValues: 'traditional',
    aboutMe: 'Dedicated medical professional with deep roots in culture. Looking for an educated partner.',
    primaryPhoto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    photos: ['https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80'],
    photoVisibility: 'public',
    biodataVisibility: 'public',
    completionPercentage: 92,
    isVerified: true,
    isFeatured: true,
    matchPercentage: 90,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_sneha',
    user: {
      _id: 'usr_sneha',
      fullName: 'Sneha Shinde',
      email: 'sneha@example.com',
      mobile: '9876543215',
      gender: 'female',
      isVerified: true,
      status: 'active',
      role: 'user',
    },
    profileId: 'PB-10029',
    age: 23,
    gender: 'female',
    height: "5'6\"",
    maritalStatus: 'never_married',
    religion: 'Hindu',
    caste: 'Maratha',
    subCaste: '96 Kuli',
    motherTongue: 'Marathi',
    city: 'Satara',
    state: 'Maharashtra',
    country: 'India',
    education: 'CA (Chartered Accountant)',
    college: 'ICAI India',
    occupation: 'Financial Auditor',
    company: 'Deloitte India',
    income: '14-18 LPA',
    fatherOccupation: 'Agricultural Business Officer',
    motherOccupation: 'Teacher',
    brothers: 0,
    sisters: 1,
    familyType: 'nuclear',
    familyValues: 'moderate',
    aboutMe: 'Chartered Accountant living in Pune. Love classical music, cooking Maharashtrian cuisine, and photography.',
    primaryPhoto: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    photos: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80'],
    photoVisibility: 'public',
    biodataVisibility: 'public',
    completionPercentage: 88,
    isVerified: true,
    isFeatured: true,
    matchPercentage: 84,
    createdAt: new Date().toISOString(),
  },
];

const initialSuccessStories = [
  {
    id: 'story_1',
    namesEn: 'Suyash & Priya',
    namesMr: 'सुयश आणि प्रिया',
    locationEn: 'Married Dec 2025 • Kolhapur & Pune',
    locationMr: 'विवाह: डिसेंबर २०२५ • कोल्हापूर व पुणे',
    image: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=600&q=80',
    quoteEn: 'We connected on Pavithra Bandhan and exchanged PDF biodatas securely. Within 3 months, our families met and fixed our wedding! Highly recommend the profile view alerts and privacy controls.',
    quoteMr: 'आम्ही पावित्र्य बंधन द्वारे जोडलो गेलो आणि सुरक्षितपणे PDF बायोडाटा शेअर केला. ३ महिन्यातच आमचे कुटुंब भेटले आणि लग्न जमले!',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'story_2',
    namesEn: 'Rohit & Ananya',
    namesMr: 'रोहित आणि अनन्या',
    locationEn: 'Married Feb 2026 • Mumbai & Nashik',
    locationMr: 'विवाह: फेब्रुवारी २०२६ • मुंबई व नाशिक',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
    quoteEn: 'The bilingual Marathi interface and smart caste & profession filters made our search so smooth. Thank you Pavithra Bandhan for helping us find our soulmate!',
    quoteMr: 'मराठी भाषेची सोय आणि सुयोग्य फिल्टरमुळे आमचा शोध अतिशय सोपा झाला. पावित्र्य बंधन चे मनापासून आभार!',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'story_3',
    namesEn: 'Aditya & Sneha',
    namesMr: 'आदित्य आणि स्नेहा',
    locationEn: 'Married Jan 2026 • Sambhajinagar & Satara',
    locationMr: 'विवाह: जानेवारी २०२६ • संभाजीनगर व सातारा',
    image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
    quoteEn: 'Finding an educated medical & finance professional partner was effortless. The view tracker notified me when Sneha viewed my profile!',
    quoteMr: 'शिक्षणाला साजेसा साथीदार शोधणे सोपे झाले. स्नेहाने माझे प्रोफाइल पाहिल्यावर मला लगेच व्ह्यू नोटिफिकेशन मिळाले होते!',
    createdAt: new Date().toISOString(),
  },
];

const seedData = async () => {
  console.log('🚀 Starting Cloud Firestore Data Seed...');

  // 1. Seed Member Profiles
  for (const prof of initialProfiles) {
    await setDoc(doc(db, 'profiles', prof._id), prof, { merge: true });
    console.log(`✓ Seeded profile: ${prof.user.fullName} (${prof.profileId})`);
  }

  // 2. Seed Success Stories
  for (const story of initialSuccessStories) {
    await setDoc(doc(db, 'success_stories', story.id), story, { merge: true });
    console.log(`✓ Seeded success story: ${story.namesEn}`);
  }

  // 3. Seed Default Site Content
  const siteContent = {
    heroHeadlineEn: 'Choose Your Forever',
    heroHeadlineMr: 'तुमच्या आयुष्याचा साथीदार शोधा',
    heroSubtitleEn: 'Find love on your terms with thousands of verified profiles',
    heroSubtitleMr: 'तुमच्या आवडीनुसार आणि विश्वासाने शोधा सुयोग्य स्थळे',
    supportPhone: '+91 98765 43210',
    supportEmail: 'support@pavithrabandhan.com',
    puneOffice: 'FC Road, Shivajinagar, Pune',
    mumbaiOffice: 'Nariman Point, Mumbai',
  };

  await setDoc(doc(db, 'site_content', 'main_config'), siteContent, { merge: true });
  console.log('✓ Seeded site_content configuration');

  console.log('🎉 Cloud Firestore seeding completed successfully!');
  process.exit(0);
};

seedData().catch((err) => {
  console.error('❌ Seeding failed:', err);
  process.exit(1);
});
